### ISSUE TITLE
Hide flow files

### ISSUE THREAD

**Issue by spatel626** [dceejay/electron-node-red#1]
When running the exe the flow file is saved in `C:/Users/USERNAME/.node-red` but I want to distribute my package for commercial use so I don't want users to see the flows and how the app was built on node-red.

Is there any way to package the flow files into the exe so they will be hidden from the user and just ran from the packaged application itself?

**Comment by dceejay** [comment]
The default one is electronflow.json - if you remove the ability to edit then it should never need to write it out again. Or do you want them to be able to edit that one flow only ?

**Comment by spatel626** [comment]
Thanks! I added your suggestions but  `electronflow.json` still gets generated in `C:/Users/USERNAME/.node-red` every time Node-Red.exe is executed. 

I am trying to make it so I can send out my build in a zip file with no flows visible. When Node-Red.exe is ran, then it would load up the flow file from from the build, and not create one in `.node-red` directory. I'm not sure if that is possible or not.

I removed `red_app.use(settings.httpAdminRoot,RED.httpAdmin);`

And I added the settings changes like so:
`settings.httpAdminRoot = false;
settings.readOnly = true;

// Initialise the runtime with a server and settings
RED.init(server,settings);
`

**Comment by dceejay** [comment]
there is a line 
there is a whole section (somewhere around line 46 - but depends on version you have downloaded as it's changed a lot recently) - where the userdir is setup and the file copied over... - you can propbably remove that entire section and replace it with  just `var userdir = __dirname;`
