### ISSUE TITLE
A JavaScript error occurs at launch

### ISSUE THREAD

**Issue by rei-vilo** [dceejay/electron-node-red#12]
On Windows 10 2004 and Node v12.16.3, 

```
git clone https://github.com/dceejay/electron-node-red.git
cd electron-node-red
sudo npm i -g yarn
yarn
yarn dist
dist\Node-RED Electron 1.1.0.msi
```

The following error message is displayed:

![Capture 2020-07-02 18-09-25](https://user-images.githubusercontent.com/951776/86385063-f41b5a80-bc8f-11ea-8c4f-fa34674ab101.png)

However, ignoring the error doesn't seem to have an impact on Electron-Node-RED.

**Comment by rei-vilo** [comment]
Same issue on macOS.

<img width="420" alt="Capture 2020-07-27 à 22 51 56" src="https://user-images.githubusercontent.com/951776/88590904-c8577e80-d05b-11ea-9fc1-207ac365c138.png">

**Comment by qyuie** [comment]
This error occurs in `node-red@1.1.0-beta.1` and later, but not in `1.0.6` and earlier.

I tried adding `if(files)` to line 29 of `\node_modules\@node-red\registry\lib\library.js`,
and this error didn't occur.

**Comment by dceejay** [comment]
rather than an `if(files)...` could you try adding an `if (err)...` - and printing out the err received ? (and pasting here) - thanks

**Comment by qyuie** [comment]
Hi @dceejay, I received the follwing err.
`Error: ENOENT, node_modules\@node-red\nodes\examples not found in C:\Users\***\Node-RED\electron-node-red\dist\win-unpacked\resources\app.asar`

**Comment by dceejay** [comment]
thanks

**Comment by blavka** [comment]
I have same problem. I'm debugging and finding out why, but I don't know how to edit it
./node_modules/@node-red/registry/lib/library.js 
![image](https://user-images.githubusercontent.com/22239151/92480791-ae29c800-f1e5-11ea-956f-a9b4e0705b1b.png)

If I run I get 
![image](https://user-images.githubusercontent.com/22239151/92480895-d285a480-f1e5-11ea-8efe-0daf1fe57b7d.png)

node-red try load examples for node, but examples folder is not in app.asar

**Comment by dceejay** [comment]
Hmm fix not quite working - reopened while fixing
