### ISSUE TITLE
1.3.1 Feature Not Working: NPM Support

### ISSUE THREAD

**Issue by cryptocracy** [dceejay/electron-node-red#15]
Hello,

I'm attempting a fresh setup with this `electron-node-red` v 1.3.1:

I set `functionExternalModules` as `true` as needed in the settings.

However the Setup tab in a Function node does not reveal the Modules fields as expected for npm support.

via console I `RED.settings.functionExternalModules`  which returns `false` even though file is verified via multiple editors.

via console I `RED.settings.functionExternalModules=true`, which upon reload of a Function node, i see the new Modules fields, 

Upon trying to utilize npm support & test with a simple inject->function->debugger flow, it produces output of:
`"Error: Function node not allowed to load external modules"`

I'm running on windows 10, yarn version 1.22.5, node version 14.5.1

Can anyone confirm this is problematic for them too?
If so does anyone have any suggestions on why this is happening and a way to fix it?
I really want to leverage this :)

**Comment by dceejay** [comment]
Have you edited main.js around line 139 to set up the settings as you want ?

**Comment by cryptocracy** [comment]
Per node-red version 1.3.3 I was able to install and utilized a 3rd party npm package via the Setup tab inside a Function node as expected.
Unclear if original issue was something on my end or version update fixed it, but marking this as closed.
