### ISSUE TITLE
Error Cannot fin module 'fs-extra

### ISSUE THREAD

**Issue by carflomi** [dceejay/electron-node-red#19]
Hello.
After generating the .msi file (flow works perfectly with yarn start) I get the following error.
![error](https://user-images.githubusercontent.com/25328861/137594204-7ff442a2-d804-4827-b4e6-b51040d2ac37.jpg)
Any idea where the problem might be?

Thanks in advance

**Comment by RaceTrackr** [comment]
Include this in the 'Dependencies' of the package.json:

`"fs-extra": "10.0.0"`
