### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by greatdsa** [dceejay/electron-node-red#2]
Hi, I am trying your example but getting some errors. This is the debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'clean' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle electron_node_red@0.20.5~preclean: electron_node_red@0.20.5
6 info lifecycle electron_node_red@0.20.5~clean: electron_node_red@0.20.5
7 verbose lifecycle electron_node_red@0.20.5~clean: unsafe-perm in lifecycle true
8 verbose lifecycle electron_node_red@0.20.5~clean: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\LBO3FE\.node-red\projects\electron-node-red\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\TwinCAT\Common64;C:\TwinCAT\Common32;C:\ProgramData\Oracle\Java\javapath;C:\Oracle\Oracle32\Cli11gR2040\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files\7-Zip;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Siemens\Teamcenter11.2\Visualization\Products\Mockup\ClearanceDB;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\7-Zip;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Users\LBO3FE\AppData\Local\Google\Chrome\Application;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\TwinCAT\Common64;C:\TwinCAT\Common32;C:\ProgramData\Oracle\Java\javapath;C:\Oracle\Oracle32\Cli11gR2040\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files\7-Zip;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Siemens\Teamcenter11.2\Visualization\Products\Mockup\ClearanceDB;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\7-Zip;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Users\LBO3FE\AppData\Roaming\npm;C:\Users\LBO3FE\AppData\Local\Calponia
9 verbose lifecycle electron_node_red@0.20.5~clean: CWD: C:\Users\LBO3FE\.node-red\projects\electron-node-red
10 silly lifecycle electron_node_red@0.20.5~clean: Args: [ '/d /s /c',
10 silly lifecycle   'rm -rf ./build ../electron-bin && mkdir -p ./build ../electron-bin' ]
11 silly lifecycle electron_node_red@0.20.5~clean: Returned: code: 1  signal: null
12 info lifecycle electron_node_red@0.20.5~clean: Failed to exec clean script
13 verbose stack Error: electron_node_red@0.20.5 clean: `rm -rf ./build ../electron-bin && mkdir -p ./build ../electron-bin`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid electron_node_red@0.20.5
15 verbose cwd C:\Users\LBO3FE\.node-red\projects\electron-node-red
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error electron_node_red@0.20.5 clean: `rm -rf ./build ../electron-bin && mkdir -p ./build ../electron-bin`
22 error Exit status 1
23 error Failed at the electron_node_red@0.20.5 clean script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dceejay** [comment]
Which platform are you running on ?
It was written on Mac OSX so

**Comment by greatdsa** [comment]
What should I do for Windows? 
I'm running it on Windows.

**Comment by dceejay** [comment]
change the clean script to windows equivalents - or just comment it out and delete the files by hand,

**Comment by greatdsa** [comment]
Thanks a lot @dceejay :)
