### ISSUE TITLE
The uiHost setting is ignored

### ISSUE THREAD

**Issue by riccardo-springtech** [dceejay/electron-node-red#21]
I'm developing an application that exposes some end-points on the local LAN.

I can create new end-points with the http-in block, and I can specify on which port to listen by settings the _listenPort_ setting. Unfortunately,  the parameter _settings.uiHost_ on row 142 of main.js is ignored, the server always listens on localhost (127.0.0.1) only.
I've tried to comment the parameter as suggested, and I also tried to set it to: _uiHost: "0.0.0.0",_  with no luck.

Anyone else having the same problem?

**Comment by riccardo-springtech** [comment]
Fixed by changing:
```
// Start the Node-RED runtime, then load the inital dashboard page
    server.listen(listenPort,"localhost",function() {
```
to:

```
// Start the Node-RED runtime, then load the inital dashboard page
    server.listen(listenPort,"0.0.0.0",function() {
```
In line 552 of **main.js**.

**Comment by dceejay** [comment]
I didn't want the server to be accessible remotely by default so fixed it to localhost.
Not going to change that default.
