### ISSUE TITLE
htppStatic in main.js

### ISSUE THREAD

**Issue by Snowy127** [dceejay/electron-node-red#22]
Hi.
I already have a project and I want to merge it with electron-node-red but the merger.js gives me an error, so I copied my flow to electronflow.
The problem is that I can't find where to put my static route configuration (from settings.js ) in main.js, the same with adminAuth, I hope you can help me

**Comment by dceejay** [comment]
The equivalent of the settings file is in main.js from lines 139 - 179

**Comment by Snowy127** [comment]
![image](https://user-images.githubusercontent.com/93785869/207401093-ba49ff65-623d-46a5-8c42-39e210143be7.png)
Thanks, I am trying to compile the program but it gives me an error

**Comment by dceejay** [comment]
sorry I don't use windows natively - it looks like it can't find the build tools. When I want windows I use the multi-platform builder docker container - https://www.electron.build/multi-platform-build.html and https://hub.docker.com/r/electronuserland/builder

**Comment by dceejay** [comment]
If you are changing things like the httpRoot and so on then you will need to go through main.js to make sure things like `urledit` etc (around line 18) are set correctly. As they define what pages get opened at start time.
