### ISSUE TITLE
How to upgrade to NodeRED v4 ?

### ISSUE THREAD

**Issue by Sergio-tix** [dceejay/electron-node-red#29]
I'm just trying to figure it out. Can you tell me how to update to the latest version (NodeRED v4)? Do I need to replace some files?

**Comment by dceejay** [comment]
Did you try just changing the version in the package.json ?

**Comment by dceejay** [comment]
I have pushed a new/latest version that seems to build for me - haven't done detailed checking so may have some bugs but at least it runs.
