### ISSUE TITLE
Issue: npm run build:osx fails

### ISSUE THREAD

**Issue by rei-vilo** [dceejay/electron-node-red#5]
`npm run build:osx` fails.

* macOS 10.14.5 (18F132)
* **electron-packager** installed with `npm install electron-packager -g` as per https://github.com/electron/electron-packager#installation
* `npm run build:osx` fails with the following error message:

> > electron_node_red@0.20.7 build:osx /Users/USER/electron-node-red
> > npm run pack:osx && appdmg appdmg.json ../electron-bin/Node-RED-Electron_$npm_package_version.dmg
> 
> 
> > electron_node_red@0.20.7 pack:osx /Users/USER/electron-node-red
> > electron-packager . Node-RED --icon=nodered.icns --platform=darwin --arch=x64 --out=build --overwrite
> 
> Packaging app for platform darwin x64 using electron v2.0.18
> Wrote new app to build/Node-RED-darwin-x64
> sh: appdmg: command not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! electron_node_red@0.20.7 build:osx: `npm run pack:osx && appdmg appdmg.json ../electron-bin/Node-RED-Electron_$npm_package_version.dmg`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the electron_node_red@0.20.7 build:osx script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/USER/.npm/_logs/2019-07-22T14_28_17_129Z-debug.log
> 

* /Users/USER/.npm/_logs/2019-07-22T14_28_17_129Z-debug.log contains

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'build:osx' ]
> 2 info using npm@6.10.0
> 3 info using node@v10.16.0
> 4 verbose run-script [ 'prebuild:osx', 'build:osx', 'postbuild:osx' ]
> 5 info lifecycle electron_node_red@0.20.7~prebuild:osx: electron_node_red@0.20.7
> 6 info lifecycle electron_node_red@0.20.7~build:osx: electron_node_red@0.20.7
> 7 verbose lifecycle electron_node_red@0.20.7~build:osx: unsafe-perm in lifecycle true
> 8 verbose lifecycle electron_node_red@0.20.7~build:osx: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/USER/electron-node-red/node_modules/.bin:/usr/local/opt/libxslt/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/openssl/bin:/usr/local/opt/gettext/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/gettext/bin:/usr/local/Cellar/php/7.3.3/bin/:/usr/local/opt/libpq/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/gettext/bin:/usr/local/opt/curl-openssl/bin:/usr/local/opt/openldap/sbin:/usr/local/opt/openldap/bin:/usr/local/opt/apr-util/bin:/usr/local/opt/apr/bin:/usr/local/opt/libpq/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/gettext/bin:/usr/local/opt/curl-openssl/bin:/usr/local/opt/openldap/sbin:/usr/local/opt/openldap/bin:/usr/local/opt/apr/bin:/usr/local/opt/apr-util/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/ncurses/bin:/usr/local/opt/gettext/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS
> 9 verbose lifecycle electron_node_red@0.20.7~build:osx: CWD: /Users/USER/electron-node-red
> 10 silly lifecycle electron_node_red@0.20.7~build:osx: Args: [ '-c',
> 10 silly lifecycle   'npm run pack:osx && appdmg appdmg.json ../electron-bin/Node-RED-Electron_$npm_package_version.dmg' ]
> 11 info lifecycle electron_node_red@0.20.7~build:osx: Failed to exec build:osx script
> 12 verbose stack Error: electron_node_red@0.20.7 build:osx: `npm run pack:osx && appdmg appdmg.json ../electron-bin/Node-RED-Electron_$npm_package_version.dmg`
> 12 verbose stack spawn ENOENT
> 12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
> 12 verbose stack     at ChildProcess.emit (events.js:198:13)
> 12 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 13 verbose pkgid electron_node_red@0.20.7
> 14 verbose cwd /Users/USER/electron-node-red
> 15 verbose Darwin 18.6.0
> 16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:osx"
> 17 verbose node v10.16.0
> 18 verbose npm  v6.10.0
> 19 error file sh
> 20 error code ELIFECYCLE
> 21 error errno ENOENT
> 22 error syscall spawn
> 23 error electron_node_red@0.20.7 build:osx: `npm run pack:osx && appdmg appdmg.json ../electron-bin/Node-RED-Electron_$npm_package_version.dmg`
> 23 error spawn ENOENT
> 24 error Failed at the electron_node_red@0.20.7 build:osx script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 1, true ]
> 

Any suggestion to package **electron-node-red** successfully? Thank you!

**Comment by rei-vilo** [comment]
However, running `electron-packager ~/electron-node-red Electron-Node-RED` succeeded.

**Comment by dceejay** [comment]
@rei-vilo This should now work as it now uses latest electron and electron-builder. Please use latest version and read the README
