### ISSUE TITLE
Feature request: Add Dashboard option to Electron menu

### ISSUE THREAD

**Issue by rei-vilo** [dceejay/electron-node-red#6]
The **Electron** menu lists **Console**, **Editor** and **Worldmap** options, but not the **Dashboard** option.

<img width="405" alt="Capture  2019-07-22 à 19 15 26" src="https://user-images.githubusercontent.com/951776/61651048-5b294480-acb5-11e9-9f75-fc43e30e51ad.png">

Please add a **Dashboard** option to the **Electron** menu.

Despite https://github.com/dceejay/electron-node-red/blob/3f2d047c8505d45bba1b0b92e868856766c04c1d/main.js#L169-L171

Thank you!

**Comment by rei-vilo** [comment]
Duplicating

https://github.com/dceejay/electron-node-red/blob/3f2d047c8505d45bba1b0b92e868856766c04c1d/main.js#L169-L172

as 

```
        {   label: 'Dashboard',
            accelerator: "Shift+CmdOrCtrl+D",
            click() { mainWindow.loadURL("http://localhost:"+listenPort+urldash); }
        },
        {   label: 'Dashboard',
            accelerator: "Shift+CmdOrCtrl+D",
            click() { mainWindow.loadURL("http://localhost:"+listenPort+urldash); }
        },
```

shows the **Dashboard** option.

<img width="405" alt="Capture  2019-07-22 à 21 45 19" src="https://user-images.githubusercontent.com/951776/61660510-486d3a80-acca-11e9-96e4-fcaf45e006be.png">

Rather strange!

**Comment by dceejay** [comment]
strange indeed.

**Comment by dceejay** [comment]
@rei-vilo 
This should now be fixed by complete rebuild uses latest electron and electron-builder - make sure you follow latest README.

**Comment by rei-vilo** [comment]
Thank you!
