### ISSUE TITLE
Accelerator - Failure

### ISSUE THREAD

**Issue by aco7342** [dceejay/electron-node-red#7]
Sorry for my poor English...
I'm trying to activate the editor but it fails(Using CTRL_S+SHIFTD v+ I): Template & Version below;

var template = [{
    label: "Application",
    submenu: [
        { role: 'about' },
        { type: "separator" },
        { role: 'quit' }
    ]}, {
    label: 'Node-RED',
    submenu: [
        { label: 'Dashboard',
        accelerator: "Shift+CmdOrCtrl+D",  // Ctrl+Shift+D  /// Shift+CmdOrCtrl+D
        click() { mainWindow.loadURL("http://localhost:"+uiport+url); }
        },
        { label: 'Editor',
        accelerator: "Shift+CmdOrCtrl+E", // Ctrl+Shift+I  // Shift+CmdOrCtrl+E
        click() { mainWindow.loadURL("http://localhost:"+uiport+urledit); }
        },
        { type: 'separator' },
        { label: 'Documentation',
        .......
]
		
20 Set 11:47:14:176 - [info] Nodejs Version:12.4.0
20 Set 11:47:14:179 - [info] Chrome Version:76.0.3809.139
20 Set 11:47:14:188 - [info] Electron Version:6.0.7
20 Set 11:47:14:191 - [info] Node-RED Version:0.20.8
20 Set 11:47:14:192 - [info] V8 Version:7.6.303.31-electron.0
20 Set 11:47:14:194 - [info] Platform:linux
20 Set 11:47:14:195 - [info] Archictecture:x64
20 Set 11:47:14:197 - [info] Release:4.9.0-9-amd64
20 Set 11:47:14:198 - [info] CPUs:Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2904Mhz
20 Set 11:47:14:200 - [info] TotalMem:2101657600
20 Set 11:47:14:247 - [info] FreeMem:75083776
20 Set 11:47:14:248 - [info] HostName:osboxes

Howto Fixit?

**Comment by dceejay** [comment]
Sorry - it is not clear. Have you modified the template ? Or are you saying it doesn't work as it is already ? To get to the editor it is Control - (or Command) - Shift E   (for Editor)
and D for Dashboard.

**Comment by aco7342** [comment]
Sorry for my poor english...Forgive me, i updated all packages, can you see below. i tried with x86 linux and arm linux. and got same result (Node-Red + Electron)Ctrl+Shift+I ==> worksMy best regards,Antonio Carlos........23 Set 10:48:03:582 - [info] Nodejs Version:12.4.023 Set 10:48:03:582 - [info] Chrome Version:76.0.3809.13923 Set 10:48:03:583 - [info] Electron Version:6.0.723 Set 10:48:03:583 - [info] Node-RED Version:0.20.823 Set 10:48:03:583 - [info] V8 Version:7.6.303.31-electron.023 Set 10:48:03:583 - [info] Platform:linux23 Set 10:48:03:584 - [info] Archictecture:x6423 Set 10:48:03:584 - [info] Release:4.9.0-9-amd6423 Set 10:48:03:584 - [info] CPUs:Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2904Mhz23 Set 10:48:03:589 - [info] TotalMem:210165760023 Set 10:48:03:589 - [info] FreeMem:7272038423 Set 10:48:03:593 - [info] HostName:osboxes23 Set 10:48:03:593 - [info] IpAddress:enp0s3 10.10.30.154.....19 Set 17:08:30:761 - [info] Nodejs Version:12.4.019 Set 17:08:30:761 - [info] Chrome Version:76.0.3809.14619 Set 17:08:30:762 - [info] Electron Version:6.0.1019 Set 17:08:30:762 - [info] Node-RED Version:0.20.819 Set 17:08:30:763 - [info] V8 Version:7.6.303.31-electron.019 Set 17:08:30:763 - [info] Platform:linux19 Set 17:08:30:764 - [info] Archictecture:arm19 Set 17:08:30:764 - [info] Release:4.19.66-v7+19 Set 17:08:30:765 - [info] CPUs:ARMv7 Processor rev 4 (v7l) - 1400Mhz19 Set 17:08:30:765 - [info] TotalMem:97106329619 Set 17:08:30:766 - [info] FreeMem:45431603219 Set 17:08:30:766 - [info] HostName:raspberrypi19 Set 17:08:30:767 - [info] IpAddress:eth0 10.10.30.146.....====================================================================part of main.js....var template = [{    label: "Application",    submenu: [        { role: 'about' },        { type: "separator" },        { role: 'quit' }    ]}, {    label: 'Node-RED',    submenu: [        { label: 'Dashboard',        accelerator: "Shift+CmdOrCtrl+D",        click() { mainWindow.loadURL("http://localhost:"+uiport+url); }        },        { label: 'Editor',        accelerator: "Shift+CmdOrCtrl+E",        click() { mainWindow.loadURL("http://localhost:"+uiport+urledit); }        },        { type: 'separator' },        { label: 'Documentation',        click() { require('electron').shell.openExternal('http://nodered.org/docs') }        },        { label: 'Flows and Nodes',        click() { require('electron').shell.openExternal('http://flows.nodered.org') }        },        { label: 'Google group',        click() { require('electron').shell.openExternal('https://groups.google.com/forum/#!forum/node-red') }        }    ]}, {    label: "Edit",    submenu: [        { label: "Undo", accelerator: "CmdOrCtrl+Z", selector: "undo:" },        { label: "Redo", accelerator: "Shift+CmdOrCtrl+Z", selector: "redo:" },        { type: "separator" },        { label: "Cut", accelerator: "CmdOrCtrl+X", selector: "cut:" },        { label: "Copy", accelerator: "CmdOrCtrl+C", selector: "copy:" },        { label: "Paste", accelerator: "CmdOrCtrl+V", selector: "paste:" },        { label: "Select All", accelerator: "CmdOrCtrl+A", selector: "selectAll:" }    ]}, {    label: 'View',    submenu: [        { label: 'Reload',            accelerator: 'CmdOrCtrl+R',            click(item, focusedWindow) { if (focusedWindow) focusedWindow.reload(); }        },        { label: 'Toggle Developer Tools',            accelerator: process.platform === 'darwin' ? 'Alt+Command+I' : 'Ctrl+Shift+I',            click(item, focusedWindow) { if (focusedWindow) focusedWindow.webContents.toggleDevTools(); }        },        { type: 'separator' },        { role: 'resetzoom' },        { role: 'zoomin' },        { role: 'zoomout' },        { type: 'separator' },        { role: 'togglefullscreen' },        { role: 'minimize' }    ]}];...............function createWindow() {    // Create the browser window.  >>>>Frame:false<<<<<    //splashWindow.close();    mainWindow = new BrowserWindow({     /*   frame:false,*/        show:false,        kiosk:false,        center:true,        autoHideMenuBar: true,        webPreferences: {            nodeIntegration: false        },        title: "PinTEF",    // Node-RED PinTEF        fullscreenable: true,        //titleBarStyle: "hidden",        width:  800,    /* 1024 800*/        height: 620,    /* 768 600*/        minwidth: 800,        minheight:620,        closable :false,        minimizable:true,        maximizable:false,        movable :false,        //frame:false,        icon: __dirname + "/pinbank.png",               /* "/nodered.png" */   /*     frame: false */    });    const EventEmitter = require('events');    const ee = new EventEmitter();    process.on('unhandledRejection', (reason,p) => {        console.log('Unhandled Rejection at: Promise', p, 'reason:' , reason);    })    //process.on('warning', e => console.warn(e.stack));    var webContents = mainWindow.webContents;    webContents.on('did-get-response-details', function(event, status, newURL, originalURL, httpResponseCode) {        if ((httpResponseCode == 404) && (newURL == ("http://localhost:"+uiport+url))) {            setTimeout(webContents.reload, 200);            Log('info', "Log File:"+__file__+" Line:"+__line__+" Function:"+funcname)            }        Menu.setApplicationMenu(Menu.buildFromTemplate(template));    });    // Open the DevTools.    //mainWindow.webContents.openDevTools();    mainWindow.webContents.on("new-window", function(e, url, frameName, disposition, options) {        // if a child window opens... modify any other options such as width/height, etc        // in this case make the child overlap the parent exactly...        var w = mainWindow.getBounds();        options.x = w.x;        options.y = w.y;        options.width = w.width;        options.height = w.height;        //re-use the same child name so all "2nd" windows use the same one.        //frameName = "child";    })    // Emitted when the window is closed.    mainWindow.on('closed', function() {        // Dereference the window object, usually you would store windows        // in an array if your app supports multi windows, this is the time        // when you should delete the corresponding element.        mainWindow = null;    });}===============================================================Em Dom 22/09/19 06:56, Dave Conway-Jones notifications@github.com escreveu:Sorry - it is not clear. Have you modified the template ? Or are you saying it doesn't work as it is already ? To get to the editor it is Control - (or Command) - Shift E (for Editor)and D for Dashboard.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by aco7342** [comment]
Q - Sorry - it is not clear. Have you modified the template ? Or are you saying it doesn't work as it is already ? To get to the editor it is Control - (or Command) - Shift E (for Editor)
and D for Dashboard.
R - I don´t modified the template, it is no respond using Control Key ( Shift E or Shift D). Now to Edit, i use browser(FireFox or Chrome) with "http://localhost:1880/admin" [Versions above]

**Comment by dceejay** [comment]
I'm sorry - I haven't tried it on node12 yet.
I normally build it on a Mac.

If I just run   `npm install`  in the main project directory to load the necessary libraries, 
then run `npm start`  I get the app running in a window. (showing the example dashboard). I can then see a menu top left
![image](https://user-images.githubusercontent.com/5375409/67133517-1ace5980-f205-11e9-9007-66c57805fbd7.png)
Which lets me switch by mouse if needs be. Not sure what that looks like for you.

**Comment by aco7342** [comment]
use in the same way, first install  npm, after starting npm, although not showing shortcuts, should be active.

extract from package.json
"node-red": "^0.20.5"
"node-red-dashboard "~2.15.5"
"electron": "^6.0.10",

**Comment by dceejay** [comment]
latest in my project should be
"node-red": "1.0.2",
"node-red-dashboard": "*",
"electron": "~2.0.18",

**Comment by dceejay** [comment]
Hi - I have fully updated to latest electron - and electron-builder - so a massive change.. .but all working now

https://github.com/dceejay/electron-node-red/pull/9

make sure you re-fetch latest and follow new README as it now uses yarn and not npm.
